name: Unit Tests

on:
  push:
    branches: [ main_s, develop_s ]
  pull_request:
    branches: [ main_s, develop_s ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Build and run unit tests
      run: make test-unit